sudo: required
language: node_js
node_js:
  - "6"
services:
  - docker
install:
  - echo "install nothing!"
script:
  - echo "no tests!"
after_success:
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin
  - eval $(aws ecr get-login --region us-west-2) #needs AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY envvars
  - docker build -t jbarnes .
  - docker tag jbarnes:latest 306438496077.dkr.ecr.us-west-2.amazonaws.com/jbarnes:latest
  - docker push 306438496077.dkr.ecr.us-west-2.amazonaws.com/jbarnes:latest
