version: "2"

services:
    nginx:
        build: ./nginx
        ports:
            - "80:80"
        image: 306438496077.dkr.ecr.us-west-2.amazonaws.com/nginx:latest
    jbarnes:
        build: ./jbarnes
        ports:
            - "8080"
        image: 306438496077.dkr.ecr.us-west-2.amazonaws.com/jbarnes:latest
    registry:
        build: ./registry
        ports:
            - "8081"
        image: 306438496077.dkr.ecr.us-west-2.amazonaws.com/registry:latest
    bio:
        build: ./bio
        ports:
            - "8082"
        image: 306438496077.dkr.ecr.us-west-2.amazonaws.com/bio:latest
    redis:
        ports:
            - "6379"
        image: library/redis:latest
    